### ISSUE TITLE
Establish consistent rule for use of SrcLoc fields in unannotated AST

### ISSUE THREAD

**Issue by rhymoid** [haskell-suite/haskell-src-exts#100]
Currently, the unannotated AST (`Language.Haskell.Exts.Syntax`) contains `SrcLoc` fields in arbitrary places:

* Practically all constructors of `Decl`, `ClassDecl`, `InsDecl`, `QualConDecl`, `GadtDecl`, `Match` (makes sense: every module-like name binding is covered by this)
* `ImportDecl` (makes sense: it introduces names)
* `Exp`'s `Lambda`, `Exp`'s `Proc` (kinda makes sense: it locally introduces names)
* `IPBind` (makes a little less sense, but it arguably still binds a name)
* `Exp`'s `ExpTypeSig` and `Pat`'s `PatTypeSig` (because they introduce type names, I guess?)
* `Stmt`'s `Generator` (wait)
* `Alt`, `GuardedAlt`, `GuardedRhs` (uhh... perhaps it's better to put a `SrcLoc` on `Pat`'s `PVar` instead, guys)
* `Module` (wha-)
* `ModulePragma` (what is going on?)
* `Exp`'s `XTag`/`XETag`/`XChildTag`, `Pat`'s `PXTag`/`PXETag` (I don't even)

At some places, the use of `SrcLoc` fields is defensible, but it's quite a slippery slope from there on. I think there needs to be a clear rationale for the use of these fields (and such a rationale needs to be documented as well), or these fields need to be removed altogether.

**Comment by pjonsson** [comment]
@niklasbroberg: Who objected the last time you mentioned dropping the un-annotated AST? It's probably a good idea to flag this direction in the release notes even if we're talking about dropping the support in 3 years from now.

**Comment by pjonsson** [comment]
@mpickering: can this ticket be closed?
