### ISSUE TITLE
Parse error with promoted tuples

### ISSUE THREAD

**Issue by tensor5** [haskell-suite/haskell-src-exts#108]
This code taken from the GHC manual

    {-# LANGUAGE DataKinds, KindSignatures, TypeOperators, GADTs #-}

    module Test where

    data HList :: [*] -> * where
      HNil  :: HList '[]
      HCons :: a -> HList t -> HList (a ': t)

fails with "Parse error: ]". Same with promoted tuples.

**Comment by pjonsson** [comment]
`PromotedList` and `PromotedTuple` now take `Type` as their parameter so this bug appears fixed. The test case also passes when I try it.
