### ISSUE TITLE
Support TypeHoles

### ISSUE THREAD

**Issue by bergmark** [haskell-suite/haskell-src-exts#118]
```
λ> Language.Haskell.Exts.Annotated.parseExp "_"
ParseFailed (SrcLoc {srcFilename = "<unknown>.hs", srcLine = 1, srcColumn = 2}) "Parse error in expression: _"
```

**Comment by radix** [comment]
stylish-haskell also can't parse partial type signatures (i.e. holes in signatures), and that's more of a grave error, in that holes in signatures are actually valid programs with the PartialTypeSignatures GHC extension. I'm not sure if that should be tracked in this or a separate haskell-src-exts ticket...
