### ISSUE TITLE
exact printing does not preserve whitespace at end of line

### ISSUE THREAD

**Issue by dmwit** [haskell-suite/haskell-src-exts#167]
(Same caveat as issue #166 -- I'm not sure if this is a goal or not. Even if it is not a goal, there should probably be some discussion in the documentation about what exact printing does and doesn't promise.) Here is a short program demonstrating that exact printing swallows whitespace in a few places:

    import Language.Haskell.Exts.Annotated
    program = "main = do \n return ()"
    pprinted = case parseFileContentsWithComments defaultParseMode program of
    	ParseOk (m, cs) -> exactPrint m cs
    	_ -> error "ack"
    main = putStrLn
    	$  show pprinted
    	++ (if pprinted == program then " == " else " /= ")
    	++ show program

**Comment by mpickering** [comment]
Not going to be fixed. It would add a lot of additional complexity without any benefit.
