### ISSUE TITLE
Bug in Datakinds Support

### ISSUE THREAD

**Issue by crockeea** [haskell-suite/haskell-src-exts#185]
My original ticket is for HLint: https://github.com/ndmitchell/hlint/issues/100
Some relevant information may also be found here: https://github.com/haskell-suite/haskell-src-exts/issues/30

I don't know how HSE and HLint interact, so I can only report what is happening in HLint:

This simple code compiles with GHC:

``` haskell
{-# LANGUAGE DataKinds #-}
module Foo where

type ToList d = '[d]
```

but `hlint Foo.hs` complains:

```
testsuite/Foo.hs:4:20: Warning: Parse error: d
Found:
    module Foo where

  > type  ToList d = '[d]
```

I have hlint 1.9.12 and hse-1.16.0.1.

**Comment by ndmitchell** [comment]
@pjonsson, @crockeea - this still seems to be present in the release on Hackage (I've just had another user report it). Any chance of a Hackage version with it fixed?
