### ISSUE TITLE
GHC vs HSE: List of all extensions handled by GHC but not yet by HSE

### ISSUE THREAD

**Issue by niklasbroberg** [haskell-suite/haskell-src-exts#19]
Below is a hopefully comprehensive list of the extensions added to GHC that HSE is not yet aware of.

*    MonadComprehensions
*    TraditionalRecordSyntax
*    Safe, Unsafe, Trustworthy

Some of these will have no syntactic impact and can thus be ticked off after having been added to Language.Haskell.Exts.Extension. Those that are syntactic in nature should each be given an issue of their own, with a reference added to the list above. When fixed, remove from list.

I intend to use this list as an evolving comparison to GHC, to keep track of how we're doing.

**Comment by pjonsson** [comment]
Updated the list in the original comment again.

I'm not sure how valuable this monster-ticket that can never be closed is; each missing extension should have its own ticket. Does anyone care about this ticket in particular or can I close it?
