### ISSUE TITLE
Parse failure with singleton language pragma

### ISSUE THREAD

**Issue by tonyday567** [haskell-suite/haskell-src-exts#195]
A parse failure occurs with:

    parseModuleWithComments defaultParseMode "{-# LANGUAGE BangPatterns #-}"

I realise that the text doesn't classify as a complete module.  Using module parsing, however, seems to be the idiomatic way to parse shorter phrases out in the wild. 

Similar phrases parse well:

    λ> parseModuleWithComments defaultParseMode "{-# LANGUAGE BangPatterns #-}"
    ParseFailed (SrcLoc "<unknown>.hs" 1 30) "Parse error: EOF"
    λ> parseModuleWithComments defaultParseMode "{- -}"
    ParseOk (Module (SrcSpanInfo {srcInfoSpan = SrcSpan "<unknown>.hs" 1 6 1 6, srcInfoPoints = [SrcSpan "<unknown>.hs" 1 6 1 6,SrcSpan "<unknown>.hs" 1 6 1 6,SrcSpan "<unknown>.hs" 1 6 1 6,SrcSpan "<unknown>.hs" 1 6 1 6]}) Nothing [] [] [],[Comment True (SrcSpan "<unknown>.hs" 1 1 1 6) " "])
    λ> parseModuleWithComments defaultParseMode ""
    ParseOk (Module (SrcSpanInfo {srcInfoSpan = SrcSpan "<unknown>.hs" 1 1 1 1, srcInfoPoints = [SrcSpan "<unknown>.hs" 1 1 1 1,SrcSpan "<unknown>.hs" 1 1 1 1,SrcSpan "<unknown>.hs" 1 1 1 1,SrcSpan "<unknown>.hs" 1 1 1 1]}) Nothing [] [] [],[])

**Comment by niklasbroberg** [comment]
```haskell
λ> parseModuleWithComments defaultParseMode "{-# LANGUAGE BangPatterns #-}\n"
ParseOk (Module (SrcLoc {srcFilename = "<unknown>.hs", srcLine = 1, srcColumn =
1}) (ModuleName "Main") [LanguagePragma (SrcLoc {srcFilename = "<unknown>.hs", s
rcLine = 1, srcColumn = 1}) [Ident "BangPatterns"]] Nothing (Just [EVar (UnQual
(Ident "main"))]) [] [],[])
```
Which, I agree, is rather inconsistent. Restructuring the various ```toppragmas``` rules in the parser likely does the trick.

**Comment by tonyday567** [comment]
Good enough for my use case but.  Thanks - I wouldn't have spotted this in a hurry!
