### ISSUE TITLE
Migrate issues from http://trac.haskell.org/haskell-src-exts/

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#198]
I can find old issues on that trac that haven't been imported. I suspect many need closing.

**Comment by niklasbroberg** [comment]
Hmm, anything specific? When migrating to github originally, I brought over only the issues that I considered to still be open. Do you want us to migrate the rest as well, for history's sake? I no longer had (have) admin rights there (trac buggy), so I couldn't close them over there.

**Comment by ndmitchell** [comment]
I only spotted this because I was going through old code which had two references to tickets on the trac, I followed the trac, found it was present but not closed, tried to reproduce and it has been fixed. If you've migrated over what is relevant, perhaps add a note to the trac? Or maybe its fine as it is - certainly no point migrating historical issues.
