### ISSUE TITLE
Pretty printing kind signatures is wrong

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#202]
Given:

    import Language.Haskell.Exts
    main = putStrLn $ prettyPrint $ fromParseResult $ parseDeclWithMode
        defaultParseMode{extensions=map EnableExtension [minBound..maxBound]}
        "type SEither (z_aizC :: Either a_a7md b_a7me) = Sing z_aizC"

I get:

    type SEither (z_aizC :: Either (a_a7md b_a7me)) = Sing z_aizC

I would expect the same input I got in. In particular, note the invalid (semantics changing) brackets around the `Either` arguments.

**Comment by mpickering** [comment]
I think this example should just require `PolyKinds` (which entails KindSignatures) but HSE also needs `DataKinds`, is my understanding correct or is DataKinds also needed in this example?

**Comment by mpickering** [comment]
Output: 

```
TypeDecl
  (SrcLoc "<unknown>.hs" 1 1)
  (Ident "SEither")
  [ KindedVar
      (Ident "z_aizC")
      (KindApp
         (KindVar (UnQual (Ident "Either")))
         (KindApp
            (KindVar (UnQual (Ident "a_a7md")))
            (KindVar (UnQual (Ident "b_a7me")))))
  ]
  (TyApp (TyCon (UnQual (Ident "Sing"))) (TyVar (Ident "z_aizC")))
```

The parser parses with the wrong associativity.

**Comment by mpickering** [comment]
Turns out there was quite a bit wrong with the KindSignatures parsing but should all be fixed now.

**Comment by ndmitchell** [comment]
Thanks @mpickering !
