### ISSUE TITLE
Parsing and exact printing of infix patterns fails

### ISSUE THREAD

**Issue by evolutics** [haskell-suite/haskell-src-exts#205]
The following program parses source code from stdin and exactly prints its AST to stdout:
```Haskell
import qualified Language.Haskell.Exts.Annotated as Annotated

main :: IO ()
main = getContents >>= putStrLn . parseAndPrint

parseAndPrint :: String -> String
parseAndPrint sourceCode = Annotated.exactPrint ast comments
  where ast = Annotated.fromParseResult $ Annotated.parseModule sourceCode
        comments = []
```

On the input
```Haskell
first :: [a] -> [a] -> [a]
[] `first` right = right
left `first` _ = left
```
it fails with an error

    ExactP: Name (epInfixName) is given wrong number of srcInfoPoints

However, it succeeds on the input
```Haskell
first :: [a] -> [a] -> [a]
first [] right = right
first left _ = left
```

**Comment by mpickering** [comment]
I've fixed this issue but I guess there are many more cases like this? Did you get much further trying to use the exact printer?

**Comment by evolutics** [comment]
Thanks a lot! I haven't checked it yet, but if it resolves this case, then that's great.
