### ISSUE TITLE
Parse fails: subtraction of lifted naturals

### ISSUE THREAD

**Issue by adituv** [haskell-suite/haskell-src-exts#206]
I get parser fails when using subtraction on lifted naturals in a type signature; I'm using the current (as of time of posting) master branch from github.

Some examples:

    import Language.Haskell.Exts
    exts = map EnableExtension [DataKinds, KindSignatures, TypeOperators, GADTs]

    -- Test cases
    decls = ["data Vec (n :: Nat) where { VCons :: (m ~ (n-1)) => Double -> Vec m -> Vec n }"
            ,"data Vec (n :: Nat) where { VCons :: ((n-1) ~ m) => Double -> Vec m -> Vec n }"
            ,"data Vec (n :: Nat) where { VCons :: ((m+1) ~ n) => Double -> Vec m -> Vec n }"
            ,"data Vec (n :: Nat) where { VCons :: (n ~ (m+1)) => Double -> Vec m -> Vec n }"
            ]

    main = mapM_ print $ map (parseDeclWithMode m) decls
      where
        m = defaultParseMode {extensions=exts}

The first two fail; the next two parse.

    ParseFailed (SrcLoc "<unknown>.hs" 1 45) "Parse error: -"
    ParseFailed (SrcLoc "<unknown>.hs" 1 41) "Parse error: -"
    ParseOk (GDataDecl (SrcLoc "<unknown>.hs" 1 1) DataType [] (Ident "Vec") [KindedVar (Ident "n") (KindVar (UnQual (Ident "Nat")))] Nothing [GadtDecl (SrcLoc "<unknown>.hs" 1 29) (Ident "VCons") [] (TyForall Nothing [ParenA (EqualP (TyParen (TyInfix (TyVar (Ident "m")) (UnQual (Symbol "+")) (TyPromoted (PromotedInteger 1)))) (TyVar (Ident "n")))] (TyFun (TyCon (UnQual (Ident "Double"))) (TyFun (TyApp (TyCon (UnQual (Ident "Vec"))) (TyVar (Ident "m"))) (TyApp (TyCon (UnQual (Ident "Vec"))) (TyVar (Ident "n"))))))] [])
    ParseOk (GDataDecl (SrcLoc "<unknown>.hs" 1 1) DataType [] (Ident "Vec") [KindedVar (Ident "n") (KindVar (UnQual (Ident "Nat")))] Nothing [GadtDecl (SrcLoc "<unknown>.hs" 1 29) (Ident "VCons") [] (TyForall Nothing [ParenA (EqualP (TyVar (Ident "n")) (TyParen (TyInfix (TyVar (Ident "m")) (UnQual (Symbol "+")) (TyPromoted (PromotedInteger 1)))))] (TyFun (TyCon (UnQual (Ident "Double"))) (TyFun (TyApp (TyCon (UnQual (Ident "Vec"))) (TyVar (Ident "m"))) (TyApp (TyCon (UnQual (Ident "Vec"))) (TyVar (Ident "n"))))))] [])

**Comment by mpickering** [comment]
Reproduced and fixed. This is because `-` is lexed to a token whilst `+` is not. There might be some more cases like this but I have fixed the specific one.
