### ISSUE TITLE
Building as a sandbox dependency in parallel sometimes fails

### ISSUE THREAD

**Issue by spl** [haskell-suite/haskell-src-exts#209]
I'm not sure if this is a `haskell-src-exts` bug or a `cabal` bug. I've only seen the problem with `haskell-src-exts`, but that's not conclusive, of course.

Occasionally, when I do

```
cabal --require-sandbox install -j --enable-tests --only-dependencies --force-reinstalls .
```

on a local sandboxed package, it fails to build `haskell-src-exts`. The only thing I get from the log is:

```
Configuring haskell-src-exts-1.16.0.1...
Building haskell-src-exts-1.16.0.1...
Preprocessing library haskell-src-exts-1.16.0.1...
[ 1 of 22] Compiling Language.Haskell.Exts.Annotated.Syntax ( src/Language/Haskell/Exts/Annotated/Syntax.hs, dist/dist-sandbox-99fd54df/build/Language/Haskell/Exts/Annotated/Syntax.o )
[ 2 of 22] Compiling Language.Haskell.Exts.ParseSyntax ( src/Language/Haskell/Exts/ParseSyntax.hs, dist/dist-sandbox-99fd54df/build/Language/Haskell/Exts/ParseSyntax.o )
[ 3 of 22] Compiling Language.Haskell.Exts.Annotated.Build ( src/Language/Haskell/Exts/Annotated/Build.hs, dist/dist-sandbox-99fd54df/build/Language/Haskell/Exts/Annotated/Build.o )
[ 4 of 22] Compiling Language.Haskell.Exts.SrcLoc ( src/Language/Haskell/Exts/SrcLoc.hs, dist/dist-sandbox-99fd54df/build/Language/Haskell/Exts/SrcLoc.o )
[ 5 of 22] Compiling Language.Haskell.Exts.Comments ( src/Language/Haskell/Exts/Comments.hs, dist/dist-sandbox-99fd54df/build/Language/Haskell/Exts/Comments.o )
[ 6 of 22] Compiling Language.Haskell.Exts.Annotated.ExactPrint ( src/Language/Haskell/Exts/Annotated/ExactPrint.hs, dist/dist-sandbox-99fd54df/build/Language/Haskell/Exts/Annotated/ExactPrint.o )
[ 7 of 22] Compiling Language.Haskell.Exts.Extension ( src/Language/Haskell/Exts/Extension.hs, dist/dist-sandbox-99fd54df/build/Language/Haskell/Exts/Extension.o )
[ 8 of 22] Compiling Language.Haskell.Exts.ExtScheme ( src/Language/Haskell/Exts/ExtScheme.hs, dist/dist-sandbox-99fd54df/build/Language/Haskell/Exts/ExtScheme.o )
[ 9 of 22] Compiling Language.Haskell.Exts.Syntax ( src/Language/Haskell/Exts/Syntax.hs, dist/dist-sandbox-99fd54df/build/Language/Haskell/Exts/Syntax.o )
```

I can rerun the above `cabal` command, and `haskell-src-exts` will build, along with the rest of my dependencies.

I really can't explain why this is happening, why only `haskell-src-exts` exhibits the problem, and why it is infrequent. I'm not exactly sure what anybody can do about it. Nonetheless, I thought I'd leave it here to see if anybody else saw this problem.

This is my current system configuration, though I believe I saw this problem also with previous versions of `cabal-install` and `ghc`: Linux, `cabal-install` 1.20.0.3, `Cabal` 1.20.0.1, `ghc` 7.8.3.

**Comment by niklasbroberg** [comment]
Off the top of my head, could this be a question of a premature time-out? L.H.E.Syntax takes a really long time to build (as does L.H.E.A.Syntax, which is built first in your example).

**Comment by hesselink** [comment]
Another suggestion: could it be that your GHC is running out of memory? I've seen cabal runs just cut short like this when that GHC ran out of memory. You should be able to find something in the syslog about that, I think (`/var/log/syslog` on Linux, `/var/log/system.log` on Mac).

**Comment by spl** [comment]
It happened again, and I think @hesselink hit the nail on the head:

```
$ cat /var/log/syslog
[...]
Mar  5 05:05:44 ubuntu kernel: [18164.391642] Out of memory: Kill process 8219 (ghc) score 321 or sacrifice child
Mar  5 05:05:44 ubuntu kernel: [18164.391645] Killed process 8219 (ghc) total-vm:1714428kB, anon-rss:351692kB, file-rss:0kB
```

I'm running a VM with Ubuntu 13.10 and 2 GB of memory.

Is this _really_ not enough memory?

**Comment by spl** [comment]
I just updated GHC from 7.8.3 to 7.8.4 and got a nice new error message:

```
Configuring persistent-template-2.1...
[ 1 of 28] Compiling Web.Stripe.Client.Util ( src/Web/Stripe/Client/Util.hs, dist/dist-sandbox-99fd54df/build/Web/Stripe/Client/Util.o )
[ 2 of 28] Compiling Web.Stripe.Client.Error ( src/Web/Stripe/Client/Error.hs, dist/dist-sandbox-99fd54df/build/Web/Stripe/Client/Error.o )
[ 3 of 28] Compiling Web.Stripe.Client.Types ( src/Web/Stripe/Client/Types.hs, dist/dist-sandbox-99fd54df/build/Web/Stripe/Client/Types.o )
[ 4 of 28] Compiling Web.Stripe.Client.Internal ( src/Web/Stripe/Client/Internal.hs, dist/dist-sandbox-99fd54df/build/Web/Stripe/Client/Internal.o )
[ 5 of 28] Compiling Web.Stripe.Types ( src/Web/Stripe/Types.hs, dist/dist-sandbox-99fd54df/build/Web/Stripe/Types.o )
ghc: out of memory (requested 1048576 bytes)
```

This happened in parallel with building `haskell-src-exts`, which completed successfully.

So, this clearly isn't a problem with `haskell-src-exts`, and I clearly need to put more RAM in my VM.
