### ISSUE TITLE
Support Haddock comments and linking them back to whatever they apply to

### ISSUE THREAD

**Issue by JPMoresmau** [haskell-suite/haskell-src-exts#213]
Hello, I would like to have the possibility for haskell-src-exts to link Haddock comments to the construct they apply to. I see this was asked on cafe a couple of years ago (https://mail.haskell.org/pipermail/haskell-cafe/2013-August/109764.html) but I don't see anything in the source base, so I suppose the situation hasn't changed.
I suggest that I go ahead and try to implement it, since I've done it before (https://github.com/JPMoresmau/BuildWrapper/blob/master/src/Language/Haskell/BuildWrapper/Src.hs#L218). The code needs to be cleaned up, made clearer, etc.
I suppose that at the start it could be made available as a standalone function. I suppose the easiest would be to change the annotation on the AST from SrcSpan to (SrcSpan,Comment).

Any remarks/requirements before I start working on it? Thanks!

**Comment by Lemmih** [comment]
Any news on this? I haven't looked over the PR in great detail but this is a feature I desire greatly.

**Comment by JPMoresmau** [comment]
Well, I've sent a pull request some time ago to address it (https://github.com/haskell-suite/haskell-src-exts/pull/225). It seems now the travis build is complaining about something, I'll have a look.

**Comment by JPMoresmau** [comment]
Travis failure is unrelated to my changes, some dependency fails to install in one GHC version. As far as I'm concerned, the functionality is done in the PR.

**Comment by Lemmih** [comment]
@feuerbach @niklasbroberg Any word on this?

**Comment by feuerbach** [comment]
I don't work on HSE anymore, so, no.

**Comment by Lemmih** [comment]
@niklasbroberg Do you want to deputize a new maintainer? If so, I volunteer.

**Comment by hesselink** [comment]
@Lemmih There was a [haskell-cafe thread about the maintainership of haskell-src-exts](https://groups.google.com/forum/#!msg/haskell-cafe/XeVn-srwK10/XY7hJi-aojYJ) recently. I think the conclusion was that @pjonsson is still the primary maintainer, so I think he would be the person to add you.

**Comment by Lemmih** [comment]
@pjonsson It seems that both Christian Marie and I are volunteering. The more the merrier, I say. What do you think?

**Comment by Lemmih** [comment]
No reply on github. I've emailed @pjonsson directly.
