### ISSUE TITLE
Getting parse error for promoted list with type variables

### ISSUE THREAD

**Issue by mageshb** [haskell-suite/haskell-src-exts#214]
Following code fails will parse error
type Foo pm = '[pm]
 20 17) "Parse error: pm"

But if i have concrete type inside promoted list, it works fine. Eg.
 type Foo = '[Int]

**Comment by mpickering** [comment]
This is fixed in HEAD.

**Comment by pjonsson** [comment]
Closing ticket since this is fixed.
