### ISSUE TITLE
Promoted lists syntactic sugar

### ISSUE THREAD

**Issue by tensor5** [haskell-suite/haskell-src-exts#219]
Last line in the following code

    {-# LANGUAGE DataKinds, GADTs, KindSignatures, TypeOperators  #-}
    
    module Test where
    
    data HList :: [*] -> * where
      HNil  :: HList '[]
      HCons :: a -> HList t -> HList (a ': t)
    
    type Foo a = HList '[a]

fails with "Parse error: a".
It parses if replaced by:

    type Foo a = HList (a ': '[])

**Comment by mpickering** [comment]
I am unable to reproduce this with the latest version. What version of HSE are you using?

```
*Language.Haskell.Exts> parseFile "test.hs"
ParseOk (Module (SrcLoc "test.hs" 1 1) (ModuleName "Test") [LanguagePragma (SrcLoc "test.hs" 1 1) [Ident "DataKinds",Ident "GADTs",Ident "KindSignatures",Ident "TypeOperators"]] Nothing Nothing [] [GDataDecl (SrcLoc "test.hs" 5 1) DataType [] (Ident "HList") [] (Just (KindFn (KindList [KindStar]) KindStar)) [GadtDecl (SrcLoc "test.hs" 6 7) (Ident "HNil") [] (TyApp (TyCon (UnQual (Ident "HList"))) (TyPromoted (PromotedList True []))),GadtDecl (SrcLoc "test.hs" 7 7) (Ident "HCons") [] (TyFun (TyVar (Ident "a")) (TyFun (TyApp (TyCon (UnQual (Ident "HList"))) (TyVar (Ident "t"))) (TyApp (TyCon (UnQual (Ident "HList"))) (TyParen (TyApp (TyApp (TyVar (Ident "a")) (TyPromoted (PromotedCon True (Special Cons)))) (TyVar (Ident "t")))))))] [],TypeDecl (SrcLoc "test.hs" 9 1) (Ident "Foo") [UnkindedVar (Ident "a")] (TyApp (TyCon (UnQual (Ident "HList"))) (TyPromoted (PromotedList True [TyVar (Ident "a")])))])
```

**Comment by tensor5** [comment]
I'm using the latest Hackage release: `1.16.0.1`.

**Comment by mpickering** [comment]
It has been fixed since then but not released yet.

**Comment by tensor5** [comment]
Thank you.

If you don't mind I would like to keep it open until the release.

**Comment by pjonsson** [comment]
Uhm, what action should we take to resolve this issue beyond parsing the example you gave?

**Comment by tensor5** [comment]
Ok.
