### ISSUE TITLE
Export `pretty` method

### ISSUE THREAD

**Issue by osa1** [haskell-suite/haskell-src-exts#222]
I'm embedding `haskell-src-exts` expressions in some structures and I can't print these structures properly without this method.

Best thing I can do without exposed `prettty :: a -> Doc` method is to use `wl-pprint`'s [string](http://hackage.haskell.org/package/wl-pprint-1.2/docs/Text-PrettyPrint-Leijen.html#v:string), but even that is printing messed up things sometimes. (for example, if it's output is small enough it's removing newlines without removing indentations)

**Comment by mpickering** [comment]
Just so I understand a bit better. You want access to the underlying representation? In that case then 

```
type Doc = DocM PPHsMode P.Doc
newtype DocM s a = DocM (s -> a)
```

So it would be necessary to also expose DocM as well, would it be better to expose a function `foo :: Pretty a => a -> P.Doc` for your use case?

**Comment by osa1** [comment]
Personally I don't need `DocM`, getting the internal `Doc` is sufficient. `foo :: Pretty a => a -> P.Doc` would work perfectly.

To rephrase my motivation; I have some data types that have `haskell-src-exts` syntax nodes as fields, and I'm trying to pretty print them. Currently there's no easy way to do that because `haskell-src-exts` isn't providing `Doc` to us, so I can't use `haskell-src-exts` outputs in my printers without messing with indentation levels, newlines etc.

**Comment by mpickering** [comment]
Hopefully this patch is suitable for your needs?

https://github.com/haskell-suite/haskell-src-exts/pull/258
