### ISSUE TITLE
Off by one in literate Haskell line numbers

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#226]
From http://trac.haskell.org/haskell-src-exts/ticket/196

    parseFileContents "{-# LINE 1 \"foo\" #-}\n\na=1"

This puts the "a=1" bit on line 3, where it should be on line 2. Confirmed to still be an issue.

**Comment by mpickering** [comment]
I can't reproduce this. There is support for LINE pragmas in the lexer.

**Comment by mpickering** [comment]
Oh wait a minute, I actually can.

**Comment by mpickering** [comment]
The simple reason for this is `defaultParseMode` ignores LINE pragmas. It seems like you figured this out as HLint give the right line numbers. The next question is why this might be desirable.

**Comment by ndmitchell** [comment]
There are a lot of bugs with cpphs and Line pragmas and HSE. This is merely one of the ones I could isolate. Once fixed, I hope to find more.

**Comment by mpickering** [comment]
```
*Language.Haskell.Exts> parseFileContentsWithMode defaultParseMode { ignoreLinePragmas = False } "{-# LINE 1 \"foo\" #-}\n\na=1"
ParseOk (Module (SrcLoc "foo" 2 1) (ModuleName "Main") [] Nothing (Just [EVar NoNamespace (UnQual (Ident "main"))]) [] [PatBind (SrcLoc "foo" 2 1) (PVar (Ident "a")) (UnGuardedRhs (Lit (Int 1))) Nothing])
```

Is that not correct?

**Comment by pjonsson** [comment]
Neil, based on Matthew's test this appears to do the thing you expect it to do if you disable `ignoreLinePragmas`. Can we close this ticket?

**Comment by ndmitchell** [comment]
@pjonsson, give me a few days to catch up with my HLint work (might be early next week) - I had big test cases that fell over in either cpphs or HSE, but as soon as I went hunting I tripped into HSE bugs without every tracking down the route causes. I'll try again with HSE head and see what I see.

**Comment by pjonsson** [comment]
Adding the 1.17 milestone for this for now. We can always unassign the milestone if we decide it shouldn't be fixed for 1.17.

**Comment by ndmitchell** [comment]
I found the original bug that started this at https://code.google.com/p/ndmitchell/issues/detail?id=331, and it is still present. Given the two line file of a blank line then:

    > main = print ([1] ++ [2, 3])

In a file Sample.lhs, running it suggests:

    C:\Neil\hlint>hlint Sample.lhs
    Sample.lhs:3:17: Warning: Use :
    Found:
      [1] ++ [2, 3]
    Why not:
      1 : [2, 3]

Note the incorrect line number. This is not using the HEAD of HSE, and the bug may really be in cpphs. If no one else gets to it, I'll try and do some initial investigation over the weekend to pinpoint HSE or cpphs.

**Comment by ndmitchell** [comment]
Note this may well be an HLint bug of passing incorrect flags, so I'll check that too.

**Comment by ndmitchell** [comment]
Running through parseFile directly works, so the bug is either only triggered by the particular way I'm calling HSE (after going through cpphs, with various options set), or by HLint itself. Moving it to the HLint tracker, since the raw HSE functionality seems to work just fine.
