### ISSUE TITLE
Parse error when using type-level subtraction

### ISSUE THREAD

**Issue by eigengrau** [haskell-suite/haskell-src-exts#230]
I’ve seen both stylish-haskell and [hlint](https://github.com/ndmitchell/hlint/issues/141) choke on the GHC.TypeLits type-level subtraction operator. Since I figure haskell-src-exts does all the parsing for these tools, I’d report this here.

```
tail ∷ (CmpNat ν 0 ~ 'GT) ⇒ Vector α ν → Vector α (ν - 1)
```

When `-` is replaced by `+`, the parse goes through just fine.

**Comment by ndmitchell** [comment]
@eigengrau can you list the GHC extensions you have on for that module, so it can be reproduced with HSE on its own?

**Comment by eigengrau** [comment]
Here’s a minimal example.

```
{-# LANGUAGE DataKinds           #-}
{-# LANGUAGE TypeOperators       #-}
{-# LANGUAGE UnicodeSyntax       #-}

module Foo where

import GHC.TypeLits
import Data.Proxy

works ∷ Proxy ν → Proxy (ν + 1)
works = undefined

fails ∷ Proxy ν → Proxy (ν - 1)
fails = undefined
```

**Comment by pjonsson** [comment]
This is now fixed in HEAD.

**Comment by eigengrau** [comment]
Thanks!
