### ISSUE TITLE
checkPattern loses positional information

### ISSUE THREAD

**Issue by mpickering** [haskell-suite/haskell-src-exts#231]
[Here](https://github.com/haskell-suite/haskell-src-exts/blob/master/src/Language/Haskell/Exts/ParseUtils.hs#L394) the position of `PApp` should not be the same as that of `Con`.

**Comment by pjonsson** [comment]
I would have expected a test output to be changed as well in this pull request. Since it doesn't seem we have one already, could you add another commit with a test for this issue?

**Comment by pjonsson** [comment]
Wrong ticket. Copying text to #233.
