### ISSUE TITLE
New dabbrev completions too eager

### ISSUE THREAD

**Issue by geraldus** [haskell-suite/haskell-src-exts#234]
Currently I'm writing some GHCJS code and didn't setup interactive version yet, so I always have dabbrev completions.  With 10-20 opened buffers dabbrev completion method becomes too eager already, i.e. completions takes too long.  It is possible to limit dabbrev list of buffers to search completions.  For example, try to lookup nearest folder contains `.git`, or `.cabal` file, set some `haskell-completions-top-folder` local var, and when searching dynamic abbrevs take this var in account.  When session is available, search for d-abbrevs in buffers assigned to current session.

What do you think?

**Comment by mpickering** [comment]
Is this in the correct repo?

**Comment by geraldus** [comment]
Wow, @mpickering of course it is not! I have no idea how could I mistook this repo! Thanks and apologize!
