### ISSUE TITLE
haskell-src-exts-1.16.0.1 won't install w/o "happy" / happy dep broken

### ISSUE THREAD

**Issue by oneeyedziggy** [haskell-suite/haskell-src-exts#240]
I'm admittedly ignorant of precisely why, but setting up some haskell packages for OsCon, I found that, at least on OSX 10.9.5, haskell-src-exts-1.16.0.1 won't install, and install fails with the message:

"haskell-src-exts-1.16.0.1 failed during the configure step. The exception was:
ExitFailure 1"

earlier in the install output is "setup-Simple-Cabal-1.22.2.0-x86_64-osx-ghc-7.10.1: The program 'happy' version
>=1.17 is required but it could not be found."

Though subsequently running "cabal install happy" worked fine and allowed me to then successfully install haskell-src-exts-1.16.0.1. 

Sorry if this is a red herring, just didn't see an issue filed yet, and I'm apparently not the only one having this issue: https://github.com/SublimeHaskell/SublimeHaskell/issues/184

**Comment by hesselink** [comment]
Cabal doesn't install build tools, this is a [known cabal issue](https://github.com/haskell/cabal/issues/220).
