### ISSUE TITLE
failure to parse trailing where

### ISSUE THREAD

**Issue by elaforge** [haskell-suite/haskell-src-exts#25]
The following code fails to parse:

```haskell
module Error where

fail = x
    where
    broken = 24
        where
    x = 413
```

The problem is the trailing 'where' after 'broken', and the dedented
'x = 413' underneath.  I think this trailing where should be legal,
from the 2010 report, section 2.7 (layout): If the indentation of the
non-brace lexeme immediately following a where, let,do or of is less
than or equal to the current indentation level, then instead of
starting a layout, an empty list “{}” is inserted, and layout
processing occurs for the current level (i.e. insert a semicolon or
close brace).

So that where should get a {} after it, and parse successfully.  Also,
haskell-src-exts is usually fine with a trailing where, but that
specific combination makes it unhappy.  And GHC has no problem with
any of it.

**Comment by mpickering** [comment]
The problem @thsutton describes is different to the original ticket which is a duplicate #228 and at least three other tickets on the tracker.

For the examaple @thsutton provides, this is what I see in HEAD.

```
instance Foo Bar where
```

```
Module
  (SrcLoc "test.hs" 1 1)
  (ModuleName "Main")
  []
  Nothing
  (Just [ EVar NoNamespace (UnQual (Ident "main")) ])
  []
  [ InstDecl
      (SrcLoc "test.hs" 1 1)
      Nothing
      []
      []
      (UnQual (Ident "Foo"))
      [ TyCon (UnQual (Ident "Bar")) ]
      []
  ]
```
