### ISSUE TITLE
Happy lower bound

### ISSUE THREAD

**Issue by asr** [haskell-suite/haskell-src-exts#250]
Given the solution for Issue https://github.com/haskell-suite/haskell-src-exts/issues/64, the lower bound for Happy should be >= 1.19.

**Comment by mpickering** [comment]
I don't think you can specify version constraints on build tools.

**Comment by asr** [comment]
Yes, you can. Tested with

```bash
$ cabal --version
cabal-install version 1.22.6.0
using version 1.22.2.0 of the Cabal library
```

**Comment by mpickering** [comment]
You're right and it always seems to have been that way.
