### ISSUE TITLE
Parse error on quasi quotes

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#259]
From http://trac.haskell.org/haskell-src-exts/ticket/214 and still confirmed as valid with HSE 1.16.0.1.

    Prelude Language.Haskell.Exts.Annotated> fmap (const ()) $ fromParseResult $ parseFileContents "{-# LANGUAGE QuasiQuotes #-}\nfoo = [$q| a b]"
    *** Exception: fromParseResult: Parse failed at [<unknown>.hs] (2:7): Unexpected end of input while lexing quasi-quoter

There was previously a reported issue with:

    {-# LANGUAGE QuasiQuotes #-}
    a = [aesonQQ|{"type": "buy", "obj_type": "catapult","x": 10.0, "y": 11.0 } |] 

But that seems to be fixed now (but might be worth a test case anyway).

**Comment by mpickering** [comment]
I don't think this is a bug. There is a missing pipe at the end of the input in your example. Adding that can it parses correctly I think.

```
{-# LANGUAGE QuasiQuotes #-}

foo = [$q| a b |]
```

```
Parse result of tests/examples/QuasiQuoteExpr2.hs:
Module () Nothing [LanguagePragma () [Ident () "QuasiQuotes"]] [] [PatBind () (PVar () (Ident () "foo")) (UnGuardedRhs () (QuasiQuote () "q" " a b ")) Nothing]
```

**Comment by ndmitchell** [comment]
Agreed, in reducing a different example I came upon an valid test case.
