### ISSUE TITLE
[Pattern synonyms] PrettyPrint CProv even if it's empty

### ISSUE THREAD

**Issue by pjonsson** [haskell-suite/haskell-src-exts#264]
This is an issue that wasn't fixed in #197. Last comment in that ticket:

Here's the example from the GHC manual:
```Haskell
pattern P :: CProv => CReq => t1 -> t2 -> ... -> tN -> t
```
The manual states "In the common case where CReq is empty, (), it can be omitted altogether.". There is no similar remark that CProv is optional which makes sense since the compiler can't know if you omitted CProv or CReq if it sees `Show a => ...` That means we can't omit `() => `in our prettyprinter and thus ppContext can't be used for c1 but it behaves the right way for c2.

**Comment by mpickering** [comment]
It is a bit more complicated still as it is possible to omit both CProv and CReq. I will look at the details later this week.
