### ISSUE TITLE
Pattern match error in the lexer

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#266]
Spotted when trying to convert Hoogle to the newest HSE, using HSE HEAD.

    C:\Neil>ghci
    GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
    Prelude> import Language.Haskell.Exts
    Prelude Language.Haskell.Exts> parseDecl "type Foo = Bar"
    *** Exception: src\Language\Haskell\Exts\ParseMonad.hs:(378,33)-(389,36): Non-exhaustive patterns in lambda

Definitely one for the 1.17 milestone.

**Comment by mpickering** [comment]
This is my fault. Writing a patch now.
