### ISSUE TITLE
Improving the output of the parser tests

### ISSUE THREAD

**Issue by mpickering** [haskell-suite/haskell-src-exts#268]
Currently it's impossible to see how the parser tests have changed because they output on one line. Would you accept a patch which either

1. Add a dependency on the `pretty-show` package and pipe the output through there before printing it.
2. Inserts a newline after every comma.
3. Something else which improves the output so it's possible to see what exactly changed when breaking the tests.

**Comment by pjonsson** [comment]
Putting this on 1.17 since the patch seems to be done already.

**Comment by pjonsson** [comment]
Fixed with 9b97af23b9aa2f94df68cdc5139ed7d208a5caff.
