### ISSUE TITLE
Parse error with bang batterns and view patterns

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#276]
From https://github.com/ndmitchell/hlint/issues/179:

    {-# LANGUAGE BangPatterns, ViewPatterns #-}
    someFun (id -> !arg) = undefined

I get:

    ParseFailed (SrcLoc "Sample.hs" 2 16) "Parse error: !"

Confirmed it reproduces with just that and just HSE.

**Comment by pjonsson** [comment]
I suspect you're running 1.16 regularly when using HLint. Is this a regression compared to 1.16?

**Comment by ndmitchell** [comment]
While I am running it regularly, I am rarely combining bang patterns and view patterns, so no real idea.

**Comment by ndmitchell** [comment]
I am pretty sure this is not a regression. However, there is a patch for it, so it would be nice to have it fixed in the new release if possible.
