### ISSUE TITLE
Remove upper bound on tasty-golden

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#281]
haskell-src-exts can no longer build with the latest tasty-golden because of the upper bound. That makes using it with stack a bit painful.

**Comment by mpickering** [comment]
https://travis-ci.org/mpickering/haskell-src-exts/jobs/93362234

Seems to cause problems building GHC 7.4. However, we can probably drop support for that now.

**Comment by ndmitchell** [comment]
To me it looks like tasty-golden has the wrong bytestring bounds, cc @feuerbach.

**Comment by mpickering** [comment]
http://matrix.hackage.haskell.org/package/tasty-golden

Looks like it works fine but the build plan is picking the bad version.

**Comment by mpickering** [comment]
I have asked the trustees to modify the bounds for tasty-golden.

**Comment by feuerbach** [comment]
So, what's the right bound?

**Comment by mpickering** [comment]
The bytestring (>= 0.10) bound which was introduced in 2.3.0.1 was backported to 2.3.0.0 as well. @phadej make the change for me. 

https://hackage.haskell.org/package/tasty-golden-2.3/tasty-golden.cabal

**Comment by ndmitchell** [comment]
Dunno, there was an error about a missing `toStrict` function? Thus I'd assume that `toStrict` got added at some version, and that's the right version?

**Comment by mpickering** [comment]
Fixed.
