### ISSUE TITLE
Parse error with view patterns (regression)

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#284]
Trying:

    {-# LANGUAGE ViewPatterns #-}
    f (id -> Just _) "" = ""

I get a parse error on the `_`. It seems view patterns with a `Just` but no brackets are bust. Reported as https://github.com/ndmitchell/hlint/issues/194 by @jasonstolaruk. This worked in the previous version, so a regression, and potentially a serious one - view patterns with `Just` are super common.

**Comment by mpickering** [comment]
Thanks for the report Neil. I am busy all of today but I can look into it tomorrow or at the weekend in more detail.

**Comment by ndmitchell** [comment]
Thanks @mpickering! Weekend is fine, just don't want to sit in the HSE repo for a full release cycle :)

**Comment by pjonsson** [comment]
Without having looked at the issue, the AST has changed in HEAD since the release so a branch is necessary for an API compatible 1.17.1 release.

**Comment by ndmitchell** [comment]
I don't mind either a 1.18 or a 1.17.1, so leave that up to you too - but good spot @pjonsson.

BTW, it might be nice if you keep the CHANGELOG updated with each relevant commit, since then it would be possible to easily see the changes from 1.17 to HEAD. I do that with my projects, and find it's also much less work to make a release.

**Comment by mpickering** [comment]
Yes @pjonsson, I was going to backport the fix to 1.17.

**Comment by mpickering** [comment]
The fix is -1 character. Going to release 1.17.1 now with the change.
