### ISSUE TITLE
Binding to a variable called "role" in do-notation fails to parse

### ISSUE THREAD

**Issue by glittershark** [haskell-suite/haskell-src-exts#288]
This may well take the cake for the strangest bug I've ever discovered.

From what I can tell (and I've done a fair amount of testing to try to narrow this down) any time I do a left-arrow-bind in do-notation to a variable with the exact name "role" in a *newer* version of haskell-src-exts (does not occur in 1.16.0.1), I get a "Parse error: Last statement in a do-block must be an expression". For example, the following fails to parse:

```haskell
foo :: Maybe Int
foo = do
    role <- Just 7
    return role
```
while the following does not:
```haskell
foo :: Maybe Int
foo = do
    rol <- Just 7
    return rol
```

Could it have something to do with -XRoleAnnotations? I don't have that enabled, but something tells me haskell-src-exts doesn't read `LANGUAGE` pragmas...

**Comment by mpickering** [comment]
`role` is a keyword when `RoleAnnotations` is turned on. Looking at the source, this seems to be the case. How are you using `haskell-src-exts`? I know some tools turn on lots of extensions to get more files to parse. 

https://github.com/haskell-suite/haskell-src-exts/blob/664023767a342f5afcbc85b60c3e2eee492f5cd1/src/Language/Haskell/Exts/InternalLexer.hs#L287

**Comment by glittershark** [comment]
I'm using it through hlint. Maybe this is actually an hlint bug, as I thought at first?

**Comment by mpickering** [comment]
So it seems that hlint turns on `RoleAnnotations` which explains the problem.

https://github.com/ndmitchell/hlint/blob/f78664477cb84573eb7ce7d72d37d9236c76073e/src/Util.hs#L125

**Comment by ndmitchell** [comment]
Even with RoleAnnotations on this should work. It's another instance of #286, which is only fixed in HEAD and not in a released version. Having it in a released version (either a back port or a new fresh version) would be useful.
