### ISSUE TITLE
Parse error with quasi quotes in types

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#289]
Reraising from #208 since I don't have permission to reopen closed tickets.

    {-# LANGUAGE QuasiQuotes #-}
    type T = [r| { foo :: Int, bar :: Bool } |]

Gives:

    ParseFailed (SrcLoc "Sample.hs" 2 10) "Parse error: [$r| { foo :: Int, bar :: Bool } ]"

Also tracked in https://github.com/ndmitchell/hlint/issues/133

**Comment by ndmitchell** [comment]
Apologies, I didn't release the ticket was closed after the last release, so fixed on HEAD (I assume).

**Comment by Rene759** [comment]
Hi there!!!
I just want to ask if it's possible if you can help me to understand how github works?
