### ISSUE TITLE
Fixites are not applied in bidirectional pattern synonyms

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#290]
Given:

    {-# LANGUAGE PatternSynonyms #-}
    pattern A <- (True, True) where A = (not $ False && True, True)
    exp = not $ False && True

The two expressions `not $ False && True` end up with different parse trees, where `exp` is correct and `pattern` is not. My guess is that HSE forgets to apply fixity resolution inside the expressions within the pattern. Reported by @divipp as https://github.com/ndmitchell/hlint/issues/212.

**Comment by pjonsson** [comment]
@mpickering: can the commit referencing this issue be whitespace-tweaked and then merged or is it still work in progress?
