### ISSUE TITLE
GHC 8.0 support

### ISSUE THREAD

**Issue by mpickering** [haskell-suite/haskell-src-exts#291]

**Comment by asr** [comment]
FYI, using GHC 8.0.1 RC 2 I could install the current master version (commit 291cc80) without problems.

**Comment by mpickering** [comment]
Thanks for testing!

An updated version of HSE with most of GHC 8.0 syntax support is on this branch as well fwiw - https://github.com/mpickering/haskell-src-exts/tree/one-ast
