### ISSUE TITLE
Kind signatures break type-level multiplication

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#298]
From https://github.com/ndmitchell/hlint/issues/227, given:

```
{-# language TypeOperators, KindSignatures #-}
data B = B
data a * b = Foo
type A = B * B
main = print 1
```

I can `runhaskell` this, but HSE complies on both uses of the `*`. Turning off `KindSignatures` makes it work once more, so seems `KindSignatures` is causing it to be incorrectly parsed.

**Comment by expipiplus1** [comment]
A workaround is to qualify the multiplication operator `a C.* b` for example

**Comment by expipiplus1** [comment]
Another workaround is to use prefix notation `(*) a b` instead of `a * b`.

**Comment by expipiplus1** [comment]
If someone could give me a couple of pointers about where to start looking at this I might be able to give it a go this weekend.

**Comment by mpickering** [comment]
I think there might need to be a special case added to the parser for `*`. I would start by looking at the parser productions for types anyway.
