### ISSUE TITLE
1.17.1 test suite failures when building with ghc 8.0.x

### ISSUE THREAD

**Issue by peti** [haskell-suite/haskell-src-exts#302]
When attempting to compile haskell-src-exts-1.17.1 with the current ghc 8.0.1-rc3 compiler, 162 out of 716 tests fail. Is that a known problem?

**Comment by pjonsson** [comment]
cc @mpickering 

Ticket #291 tracks the issue. Not sure to what extent those patches are build fixes or new features.

**Comment by mpickering** [comment]
I have released a new version, 1.18.0.
