### ISSUE TITLE
`Type` doesn't support type literals `LitT`

### ISSUE THREAD

**Issue by pseudonom** [haskell-suite/haskell-src-exts#306]
It seems to be missing the constructor here: 
https://hackage.haskell.org/package/haskell-src-exts-1.17.1/docs/Language-Haskell-Exts-Syntax.html#t:Type

How hard would it be to add this case myself? Can I just add the constructor and follow the warnings?

**Comment by mpickering** [comment]
I think you are looking for `TyPromoted`

https://hackage.haskell.org/package/haskell-src-exts-1.18.0/docs/Language-Haskell-Exts-Syntax.html#t:Type
