### ISSUE TITLE
`SrcLoc.noLoc` yields ghc-unparseable LINE pragmas

### ISSUE THREAD

**Issue by bezirg** [haskell-suite/haskell-src-exts#311]
When `SrcLoc.noLoc` is combined with `Pretty.PPHsMode {linePragmas=True}` ,
it prettyprints unparseable line pragmas as:

```haskell
{-# LINE -1 "" #-}
```

This is because `SrcLoc.noLoc` is defined as `noLoc = SrcLoc "" (-1) (-1)` and GHC
refuses to parse LINE pragmas with *NEGATIVE* lines.

Can you possibly add a check to avoid the pretty-printing of LINE pragmas containing negative lines?

**Comment by mpickering** [comment]
The current plan is to remove the unannotated tree (and thus this printing of line pragmas).

**Comment by bezirg** [comment]
Ok, understandable.

**Comment by mpickering** [comment]
It has now been removed.
