### ISSUE TITLE
{-# LANGUAGE ScopedTypeVariables #-}

### ISSUE THREAD

**Issue by ciez** [haskell-suite/haskell-src-exts#313]
when parsing module with ScopedTypeVariables pragma, this error message comes up:

["SrcLoc \"<unknown>.hs\" 27 38","\"ScopedTypeVariables language extension is not enabled. Please add {-# LANGUAGE ScopedTypeVariables #-} pragma at the top of your module.\""]

this module compiles with ghc ok

**Comment by mpickering** [comment]
I think you probably need to use `parseFileWithCommentsAndPragmas` rather than `parseFile`. The former parses the header and turns on the appropriate extensions. 

Please reopen with a more complete program if you need more help.

**Comment by ciez** [comment]
yes, you are right: changing parseModule to parseModuleWithMode did it.
ta
