### ISSUE TITLE
Request: Building combinator for easing the migration from 1.17 to 1.18

### ISSUE THREAD

**Issue by asr** [haskell-suite/haskell-src-exts#321]
In version 1.17.*, the non-annotated data constructor [`DataDecl`](http://hackage.haskell.org/package/haskell-src-exts-1.17.1/docs/Language-Haskell-Exts-Syntax.html#v:DataDecl)  has the type

```haskell
DataDecl... Name [TyVarBind]...
```

and in version 1.18.*, its type is

```haskell
DataDecl... (DeclHead l)... 
```

For easing the migration from 1.17 to 1.18, it would be great a combinator

```haskell
foo :: Name -> [TyVarBind] -> DeclHead ()
```

**Comment by mpickering** [comment]
I think `haskell-src-exts-simple` is suitable for your needs? Please reopen if I am misunderstanding.
