### ISSUE TITLE
Operator parsing issue

### ISSUE THREAD

**Issue by jaspervdj** [haskell-suite/haskell-src-exts#325]
The following file fails to parse with `Parse error: ;`

```
smaller a b  = a <b
```
Using a space in between `a` and `b` works:

```
smaller a b = a < b
```

**Comment by mpickering** [comment]
I can't reproduce this. How are you invoking HSE?

**Comment by jaspervdj** [comment]
My mistake.  I had `{-# LANGUAGE XmlSyntax #-}` enabled.  I'm not sure what the expected behaviour there is, I'm not too familiar with that extension.  I will close this issue for now.
