### ISSUE TITLE
Order of arguments in `AppA` are parsed in reverse order

### ISSUE THREAD

**Issue by chrisdone** [haskell-suite/haskell-src-exts#328]
The order of arguments in `AppA` are parsed in reverse order in this example:
``` haskell
> fmap Language.Haskell.Exts.Pretty.prettyPrint 
       (parseDeclWithMode parseMode "data Link x a b = forall b . (x a b) => Link a")
ParseOk "data Link x a b = forall b . (x b a) => Link a"
-----------------------------------------^-^
```

Related https://github.com/chrisdone/hindent/issues/278

**Comment by mpickering** [comment]
Thanks Chris. The fix is to remove the `reverse` in `checkAssertion'`. I will put the fix in the next release.
