### ISSUE TITLE
Parse error on GADT with context and records

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#329]
From https://raw.githubusercontent.com/d3sformal/bacon-core/master/src/Algorithm/Pdr/State.hs by @d3sformal I see a parse error on:

    data PdrConf d where MonadDomain d => PdrConf :: { frames :: Set d} -> PdrConf d

**Comment by mpickering** [comment]
Is this not just #324 ?

**Comment by ndmitchell** [comment]
Yep, sorry for the noise.
