### ISSUE TITLE
Support OVERLAPPING/OVERLAPPABLE/OVERLAPS pragmas

### ISSUE THREAD

**Issue by sighingnow** [haskell-suite/haskell-src-exts#354]
Currently, these three pragmas in instance declaration are treated as comments. See more detail about these pragmas [here](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#overlapping-overlappable-overlaps-and-incoherent-pragmas).

**Comment by NorfairKing** [comment]
+1
