### ISSUE TITLE
GHC 8.6 extension support?

### ISSUE THREAD

**Issue by kozross** [haskell-suite/haskell-src-exts#419]
In particular, ``DerivingVia`` is giving a lot of tooling (such as HLint and hindent) severe trouble at the moment.

**Comment by RyanGlScott** [comment]
`DerivingVia` in particular is handled in #420.

**Comment by fosskers** [comment]
It also seems that the new syntax allowed by `BlockArguments` is not parsable by `haskell-src-exts-1.21.0`.

**Comment by ttuegel** [comment]
`QuantifiedConstraints` is also not supported by `haskell-src-exts-1.21.0`.

**Comment by domenkozar** [comment]
Same for `BlockArguments`
