### ISSUE TITLE
Arrow control operators (form, banana brackets) are not supported

### ISSUE THREAD

**Issue by ghost** [haskell-suite/haskell-src-exts#45]
Currently, all Arrow notation can be parsed, except the banana brackets (which corresponds to the `form` keyword in Ross Paterson's paper), thereby making support for Arrows incomplete.

Minimal example, which parses and type-checks in GHC, and fails to parse in HSE and HSEA:

```
{-# LANGUAGE Arrows #-}
f :: a -> a
f = proc x -> (| undefined |)
```

This is also blocking me from conveniently desugaring recrusive arrow notation, which involves translation _into_ an expression that contains `form`.

**Comment by pepeiborra** [comment]
Is anyone working on this ?

**Comment by mpickering** [comment]
As far as I know, no.

**Comment by mpickering** [comment]
Also see #364
