### ISSUE TITLE
Using "*" with TypeOperators is a parse error

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#81]
See https://code.google.com/p/ndmitchell/issues/detail?id=634:

    Program.hs:4:10: Warning: Parse error: (
    Found:
        module Program
            ( Program(..)
      >     , (*)()
            , (+)()
            , Unit

    Build.hs:36:69: Warning: Parse error: *
    Found:
        dtBlock :: forall repr. (Program repr, Typeable2 repr) => DynTerm repr
      > dtBlock = DynTerm $ toDynamic (block :: repr ANY2 ANY3 -> repr (ANY * ANY1)     ((repr ANY2 ANY3 * ANY) * ANY1))

This happens even when passing -XTypeOperators. Both files compile fine under GHC (tested on 7.6.3).

**Comment by mpickering** [comment]
This appears to be fixed in HEAD.

In:
```
{-# LANGUAGE TypeOperators #-}
module PromotedTuples where

foo :: (a * b)
foo = 5
```

out:
```
Module
  (SrcLoc "test.hs" 1 1)
  (ModuleName "PromotedTuples")
  [ LanguagePragma (SrcLoc "test.hs" 1 1) [ Ident "TypeOperators" ] ]
  Nothing
  Nothing
  []
  [ TypeSig
      (SrcLoc "test.hs" 4 1)
      [ Ident "foo" ]
      (TyParen
         (TyInfix
            (TyVar (Ident "a")) (UnQual (Symbol "*")) (TyVar (Ident "b"))))
  , PatBind
      (SrcLoc "test.hs" 5 1)
      (PVar (Ident "foo"))
      (UnGuardedRhs (Lit (Int 5)))
      (BDecls [])
  ]

```

**Comment by pjonsson** [comment]
Closing since this appears fixed.
